name: Python CI with unittest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 设置超时时间

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 更新到最新版本

    - name: Set up Python
      uses: actions/setup-python@v5  # 更新到最新版本
      with:
        python-version: '3.11'  # 推荐使用更新的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        python -m unittest discover -s tests -v -b  # -b 参数禁止捕获输出

    - name: Upload test results
      if: always()  # 即使测试失败也上传
      uses: actions/upload-artifact@v4  # 使用v4版本
      with:
        name: unittest-results
        path: |
          test-reports/*.xml
          !test-reports/tmp/
        retention-days: 3  # 结果保留3天